### PR TITLE
Pixel art generation Musina Polina

### PR DESCRIPTION
**Pull request by MusinaPolina**

### CODE REVIEW

**Comment by kajigor** [comment]
Ничего не забыли закоммитить? Не собирается 

```
ev@ev:~/teach/2022/jub/proj/PolinaMusina$ stack build
Specified source-dir "src" does not exist
Trouble loading CompilerPaths cache: UnliftIO.Exception.throwString called with:

Global dump did not parse correctly
Called from:
  throwString (src/Stack/Storage/User.hs:295:20 in stack-2.9.1-6pnXUCahaPICbSEjLQ1K5Q:Stack.Storage.User)

hmatrix> configure
hmatrix> Warning: hmatrix.cabal:21:28: Packages with 'cabal-version: 1.12' or later
hmatrix> should specify a specific version of the Cabal spec of the form
hmatrix> 'cabal-version: x.y'. Use 'cabal-version: 1.18'.
hmatrix> Configuring hmatrix-0.20.2...
hmatrix> Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.5: Missing dependencies on foreign
hmatrix> libraries:
hmatrix> * Missing (or bad) C libraries: blas, lapack
hmatrix> This problem can usually be solved by installing the system packages that
hmatrix> provide these libraries (you may need the "-dev" versions). If the libraries
hmatrix> are already installed but in a non-standard location then you can use the
hmatrix> flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
hmatrix> the library files do exist, it may contain errors that are caught by the C
hmatrix> compiler at the preprocessing stage. In this case you can re-run configure
hmatrix> with the verbosity flag -v3 to see the error messages.
hmatrix>    
Progress 1/2

--  While building package hmatrix-0.20.2 (scroll up to its section to see the error) using:
      /home/ev/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.5 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.6.3.0 configure --with-ghc=/home/ev/.stack/programs/x86_64-linux/ghc-tinfo6-9.2.5/bin/ghc-9.2.5 --with-ghc-pkg=/home/ev/.stack/programs/x86_64-linux/ghc-tinfo6-9.2.5/bin/ghc-pkg-9.2.5 --user --package-db=clear --package-db=global --package-db=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/pkgdb --libdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/lib --bindir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/bin --datadir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/share --libexecdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/libexec --sysconfdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/etc --docdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --htmldir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --haddockdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --dependency=array=array-0.5.4.0 --dependency=base=base-4.16.4.0 --dependency=binary=binary-0.8.9.0 --dependency=bytestring=bytestring-0.11.3.1 --dependency=deepseq=deepseq-1.4.6.1 --dependency=primitive=primitive-0.7.3.0-AwGslPyfQNeDCHW7WoM0VU --dependency=random=random-1.2.1.1-LKI4zBxQSOx7AsuBLGiNF1 --dependency=semigroups=semigroups-0.20-Ataa94eSftS9PXhef7F53I --dependency=split=split-0.2.3.5-A3rQLwgqzsiLSLyptRyW5K --dependency=storable-complex=storable-complex-0.2.3.0-KRLknv17JlDGgcEXBrMFwZ --dependency=vector=vector-0.12.3.1-9lAFbeOos5HBZVbPp7MuQ3 -f-disable-default-paths -f-no-random_r -f-openblas --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1
```

**Comment by MusinaPolina** [comment]
Должно собираться теперь

> Ничего не забыли закоммитить? Не собирается
> 
> ```
> ev@ev:~/teach/2022/jub/proj/PolinaMusina$ stack build
> Specified source-dir "src" does not exist
> Trouble loading CompilerPaths cache: UnliftIO.Exception.throwString called with:
> 
> Global dump did not parse correctly
> Called from:
>   throwString (src/Stack/Storage/User.hs:295:20 in stack-2.9.1-6pnXUCahaPICbSEjLQ1K5Q:Stack.Storage.User)
> 
> hmatrix> configure
> hmatrix> Warning: hmatrix.cabal:21:28: Packages with 'cabal-version: 1.12' or later
> hmatrix> should specify a specific version of the Cabal spec of the form
> hmatrix> 'cabal-version: x.y'. Use 'cabal-version: 1.18'.
> hmatrix> Configuring hmatrix-0.20.2...
> hmatrix> Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.5: Missing dependencies on foreign
> hmatrix> libraries:
> hmatrix> * Missing (or bad) C libraries: blas, lapack
> hmatrix> This problem can usually be solved by installing the system packages that
> hmatrix> provide these libraries (you may need the "-dev" versions). If the libraries
> hmatrix> are already installed but in a non-standard location then you can use the
> hmatrix> flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
> hmatrix> the library files do exist, it may contain errors that are caught by the C
> hmatrix> compiler at the preprocessing stage. In this case you can re-run configure
> hmatrix> with the verbosity flag -v3 to see the error messages.
> hmatrix>    
> Progress 1/2
> 
> --  While building package hmatrix-0.20.2 (scroll up to its section to see the error) using:
>       /home/ev/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.5 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.6.3.0 configure --with-ghc=/home/ev/.stack/programs/x86_64-linux/ghc-tinfo6-9.2.5/bin/ghc-9.2.5 --with-ghc-pkg=/home/ev/.stack/programs/x86_64-linux/ghc-tinfo6-9.2.5/bin/ghc-pkg-9.2.5 --user --package-db=clear --package-db=global --package-db=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/pkgdb --libdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/lib --bindir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/bin --datadir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/share --libexecdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/libexec --sysconfdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/etc --docdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --htmldir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --haddockdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --dependency=array=array-0.5.4.0 --dependency=base=base-4.16.4.0 --dependency=binary=binary-0.8.9.0 --dependency=bytestring=bytestring-0.11.3.1 --dependency=deepseq=deepseq-1.4.6.1 --dependency=primitive=primitive-0.7.3.0-AwGslPyfQNeDCHW7WoM0VU --dependency=random=random-1.2.1.1-LKI4zBxQSOx7AsuBLGiNF1 --dependency=semigroups=semigroups-0.20-Ataa94eSftS9PXhef7F53I --dependency=split=split-0.2.3.5-A3rQLwgqzsiLSLyptRyW5K --dependency=storable-complex=storable-complex-0.2.3.0-KRLknv17JlDGgcEXBrMFwZ --dependency=vector=vector-0.12.3.1-9lAFbeOos5HBZVbPp7MuQ3 -f-disable-default-paths -f-no-random_r -f-openblas --exact-configuration --ghc-option=-fhide-source-paths
>     Process exited with code: ExitFailure 1
> ```

**Comment by kajigor** [comment]
```
/home/ev/teach/2022/jub/proj/PolinaMusina/test/Test.hs:1:1: error: unterminated `{-' at end of input
  |               
1 | {-# OPTIONS_GHC -F -pgmF tasty-discover -optF}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by kajigor** [comment]
Вы будете другие подзадачи еще делать, или ограничитесь сделанными? Сделанные: 

* Консольный (или другой пользовательский) интерфейс
* Загрузка картинки в формате png (можно пользоваться готовым загрузчиком)
* Пикселизация изображения

Дополнительные задачи:

* Возможность выбрать размер пикселя

**Comment by MusinaPolina** [comment]
Должно собираться теперь

> Ничего не забыли закоммитить? Не собирается
> 
> ```
> ev@ev:~/teach/2022/jub/proj/PolinaMusina$ stack build
> Specified source-dir "src" does not exist
> Trouble loading CompilerPaths cache: UnliftIO.Exception.throwString called with:
> 
> Global dump did not parse correctly
> Called from:
>   throwString (src/Stack/Storage/User.hs:295:20 in stack-2.9.1-6pnXUCahaPICbSEjLQ1K5Q:Stack.Storage.User)
> 
> hmatrix> configure
> hmatrix> Warning: hmatrix.cabal:21:28: Packages with 'cabal-version: 1.12' or later
> hmatrix> should specify a specific version of the Cabal spec of the form
> hmatrix> 'cabal-version: x.y'. Use 'cabal-version: 1.18'.
> hmatrix> Configuring hmatrix-0.20.2...
> hmatrix> Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.5: Missing dependencies on foreign
> hmatrix> libraries:
> hmatrix> * Missing (or bad) C libraries: blas, lapack
> hmatrix> This problem can usually be solved by installing the system packages that
> hmatrix> provide these libraries (you may need the "-dev" versions). If the libraries
> hmatrix> are already installed but in a non-standard location then you can use the
> hmatrix> flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
> hmatrix> the library files do exist, it may contain errors that are caught by the C
> hmatrix> compiler at the preprocessing stage. In this case you can re-run configure
> hmatrix> with the verbosity flag -v3 to see the error messages.
> hmatrix>    
> Progress 1/2
> 
> --  While building package hmatrix-0.20.2 (scroll up to its section to see the error) using:
>       /home/ev/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.6.3.0_ghc-9.2.5 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.6.3.0 configure --with-ghc=/home/ev/.stack/programs/x86_64-linux/ghc-tinfo6-9.2.5/bin/ghc-9.2.5 --with-ghc-pkg=/home/ev/.stack/programs/x86_64-linux/ghc-tinfo6-9.2.5/bin/ghc-pkg-9.2.5 --user --package-db=clear --package-db=global --package-db=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/pkgdb --libdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/lib --bindir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/bin --datadir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/share --libexecdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/libexec --sysconfdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/etc --docdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --htmldir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --haddockdir=/home/ev/.stack/snapshots/x86_64-linux-tinfo6/0efd752c6e09a881cefd78a2b94a74626db3675d13c87fbbd486de569b1f1c99/9.2.5/doc/hmatrix-0.20.2 --dependency=array=array-0.5.4.0 --dependency=base=base-4.16.4.0 --dependency=binary=binary-0.8.9.0 --dependency=bytestring=bytestring-0.11.3.1 --dependency=deepseq=deepseq-1.4.6.1 --dependency=primitive=primitive-0.7.3.0-AwGslPyfQNeDCHW7WoM0VU --dependency=random=random-1.2.1.1-LKI4zBxQSOx7AsuBLGiNF1 --dependency=semigroups=semigroups-0.20-Ataa94eSftS9PXhef7F53I --dependency=split=split-0.2.3.5-A3rQLwgqzsiLSLyptRyW5K --dependency=storable-complex=storable-complex-0.2.3.0-KRLknv17JlDGgcEXBrMFwZ --dependency=vector=vector-0.12.3.1-9lAFbeOos5HBZVbPp7MuQ3 -f-disable-default-paths -f-no-random_r -f-openblas --exact-configuration --ghc-option=-fhide-source-paths
>     Process exited with code: ExitFailure 1
> ```



> Вы будете другие подзадачи еще делать, или ограничитесь сделанными? Сделанные:
> 
>     * Консольный (или другой пользовательский) интерфейс
> 
>     * Загрузка картинки в формате png (можно пользоваться готовым загрузчиком)
> 
>     * Пикселизация изображения
> 
> 
> Дополнительные задачи:
> 
>     * Возможность выбрать размер пикселя

На данный момент эта функциональность тоже есть, она задается числом пикселей в сжатом пикселе после имени файла (по умолчанию 10). Так же есть возможность выбрать палитру, но нужно доделать консольный интерфейс.

**Comment by kajigor** [comment]
Ок, зачту на 28 баллов

**Pull request closed without merging**
